### ISSUE TITLE
Problem when make in build/linux

### ISSUE THREAD

**Issue by BiatBang** [CTU-IIG/macan#3]
Hi, I'm trying to use "KLEE" to test your MaCAN. When I do "make" in build/linux, something wrong like this:

/home/biat/macan/build/linux/macan/src/macan.c:122:16: error: lvalue required as unary ‘&’ operand
  memcpy(plain, &htole32(t), 4);
                ^
/home/biat/macan/build/linux/macan/src/macan.c: In function ‘receive_time_auth’:
/home/biat/macan/build/linux/macan/src/macan.c:441:21: error: lvalue required as unary ‘&’ operand
  memcpy(plain + 10, &htole32(CANID(ctx, ctx->config->time_server_id)),2);
                     ^
/home/biat/macan/build/linux/Makefile.rules:725: recipe for target 'macan.o' failed
make[4]: *** [macan.o] Error 1
/home/biat/macan/build/linux/Makefile.rules:761: recipe for target 'library-pass-this-dir' failed
make[3]: *** [library-pass-this-dir] Error 2
/home/biat/macan/build/linux/Makefile.rules:761: recipe for target 'library-pass-src-subdir' failed
make[2]: *** [library-pass-src-subdir] Error 2
/home/biat/macan/build/linux/Makefile.rules:761: recipe for target 'library-pass-macan-subdir' failed
make[1]: *** [library-pass-macan-subdir] Error 2
/home/biat/macan/build/linux/Makefile.rules:761: recipe for target 'library-pass' failed

Do you know why is that? Is it because the function is in 32-bit?

Besides, if I want to use KLEE to test the program, would you give me some advice on how to do it?
Thank you very much.

**Comment by wentasah** [comment]
Hi,

regarding klee, there is a [README](build/klee/README). It may give you some hints. I'm afraid I no longer remember how everything was done and I no longer have working setup. So if the README and the repo linked from there does not help, you have to figure out how to do it yourself.

I recall that klee-build of macan does not read packets from network/socket, but it uses symbolic data artificially pushed to it.
